name             'openpds'
maintainer       'Patrick Connolly (patcon)'
maintainer_email 'patrick.c.connolly@gmail.com'
license          'MIT'
description      'Installs/Configures openpds'
long_description 'Installs/Configures openpds'
version          '0.1.0'

depends 'git'
depends 'python'
depends 'mongodb'
depends 'postgresql'
